/* eslint-disable */
// This file is automatically generated, do not edit!

import "@atcute/client/lexicons";

declare module "@atcute/client/lexicons" {
  namespace InvalidUwxEncryptedBookmark {
    /** A bookmark. */
    interface Record {
      $type: "invalid.uwx.encrypted.bookmark";
      encryptedUrl?: At.Bytes;
    }
  }

  interface Records {
    "invalid.uwx.encrypted.bookmark": InvalidUwxEncryptedBookmark.Record;
  }

  interface Queries {}

  interface Procedures {}
}
