/* eslint-disable */
// This file is automatically generated, do not edit!

import "@atcute/client/lexicons";

declare module "@atcute/client/lexicons" {
  namespace IoGithubUwxBluemarkEncryptedBookmark {
    /** An encrypted bookmark. */
    interface Record {
      $type: "io.github.uwx.bluemark.encryptedBookmark";
      cipher: string;
      iv: string;
      salt: string;
    }
  }

  interface Records {
    "io.github.uwx.bluemark.encryptedBookmark": IoGithubUwxBluemarkEncryptedBookmark.Record;
  }

  interface Queries {}

  interface Procedures {}
}
